"""provider_price column added to products table

Revision ID: 0166ce7b8650
Revises: 9e96c7d7323a
Create Date: 2023-03-10 23:12:05.842318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0166ce7b8650'
down_revision = '9e96c7d7323a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('provider_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'provider_price')
    # ### end Alembic commands ###
