"""created_at and update_at columns added to stock table

Revision ID: 3edf2396f6e0
Revises: 06cb1872bda8
Create Date: 2023-02-24 00:04:02.256785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edf2396f6e0'
down_revision = '06cb1872bda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('stock', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'updated_at')
    op.drop_column('stock', 'created_at')
    # ### end Alembic commands ###
