"""product column name isnt unique now

Revision ID: 409a95fa73ae
Revises: 0166ce7b8650
Create Date: 2023-03-13 18:16:29.058317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409a95fa73ae'
down_revision = '0166ce7b8650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    # ### end Alembic commands ###
