"""stock_id in product table must be unique now

Revision ID: 98d28aa8d274
Revises: 3edf2396f6e0
Create Date: 2023-02-24 23:52:37.976800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d28aa8d274'
down_revision = '3edf2396f6e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['stock_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
