"""id column remove from products_listed table, created composite primarykey

Revision ID: 9e96c7d7323a
Revises: 293d0c4d7948
Create Date: 2023-03-01 20:23:10.823895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e96c7d7323a'
down_revision = '293d0c4d7948'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_listed', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_listed', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
