"""product and discount table relationship addded

Revision ID: d0f7800b9484
Revises: 3f8b425e3f76
Create Date: 2023-02-25 18:56:47.658432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f7800b9484'
down_revision = '3f8b425e3f76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'discounts', ['discount_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'discount_id')
    # ### end Alembic commands ###
